### ISSUE TITLE
trash delete ?

### ISSUE THREAD

**Issue by evanillaa** [qbcore-framework/qb-policejob#108]
["trash"] = {
       [1] = vector4(439.0907, -976.746, 30.776, 93.03),
   },

for k, v in pairs(Config.Locations["trash"]) do

Hello, I have a suggestion or request
And there's a trash can
At the police station
We need a way to make this store delete its contents after a certain period
For example, every month
I've tried through the databases to syntax to delete the content of the trash but unfortunately the results are poor
It will be a great example of dealing with databases and can be used in many places

**Comment by jnccloud** [comment]
Just thinking out loud here, but since it is considered a stash, perhaps the stash could be dynamically named to the current month - for example, _policetrash09_ instead of _policetrash_, and there could be a function that runs on resource start to delete the stash from the month before (configurable via config to 1-11 months - 1 = 1 month, 2 = 2 months, etc) to keep the bin longer if needed - one could even use the week # of the year to empty it more often. I actually just ran into this issue today on my server, so if I find a suitable solution I'll share it =)

**Comment by SamShanks1** [comment]
https://github.com/SamShanks1/qb-policejob

This will empty the police trash every restart or when the resource is loaded
