### ISSUE TITLE
I dont have the names of the vehicles showing

### ISSUE THREAD

**Issue by kelevra69** [qbcore-framework/qb-policejob#330]
I am not sure if I changed something by accident but when I go to the garage the ranks are correct for the vehicles that should be there but the names of the vehicles are not there.....just says blank space....then garage....I guess just wondering where the function or the part that tells it to look for the name of vehicle....and yes my spawn is the numbers....1,2,3,4,5...

Thanks for any assistance

![image](https://user-images.githubusercontent.com/69827063/174253964-426108ef-9f5d-4208-9f26-58ececdcf305.png)
![car](https://user-images.githubusercontent.com/69827063/174254042-b5ecd9d5-c649-44a7-970f-1daf025487ba.JPG)

**Comment by FjamZoo** [comment]
Your issue is becuase you are putting in their name and NOT the spawn code.

However I would say please update your script as we do not support anything that is this old (Must be atleast 8-9 months old) since we ditched that menu system AGES ago.

You can also join our discord for additional support: discord.gg/QBCore

**Comment by kelevra69** [comment]
OK thanks for th einfor BUT as I stated the spawn names are there so not sure what you are talking about that they arent....the cars spawn just menu has no name as I STATED in the issue....the spawn codes are 1 and 2 and 3 and 4....not sure why this was closed without it helping me at all other then telling me its old...if you know the answer could you tell me?
