### ISSUE TITLE
Heli Spawner requires cleanup on player disconnect

### ISSUE THREAD

**Issue by S33G** [qbcore-framework/qb-policejob#443]
Related to this issue: https://github.com/qbcore-framework/qb-policejob/issues/438

Helicopters are spawnable on the roof of police station. I spawned a couple of heli's a few days ago and nothing has cleaned them up from my server. `vector4(458.49, -979.65, 53.21, 100.52)`

We should implement some "garbage collection" so there's not random heli's still on the server somewhere. 

These persist with user logout / disconnect & server restart.

![image](https://user-images.githubusercontent.com/655807/212442287-8cf9e43b-0959-4bff-b313-cba160bcddb8.png)

**To Reproduce**
1. Give yourself police job `/setjob police 4`
2. Navigate here: `vector4(458.49, -979.65, 53.21, 100.52)` On the roof, can `/noclip`
3. Spawn heli's
4. Disconnect
6. Still see heli's

**Expected behavior**
Delete heli on player disconnect

**Comment by jnccloud** [comment]
Helis should be stored because another player could be using that heli. IE- Supervisor pulls it out for pilot/training. Also, the script does not spawn helicopters automatically. Spawned vehicles by default despawn after a player disconnects if there's no other clients to take ownership. I think you've got a weird edge case here, might be your server artifacts.
